# Generated by Django 5.0.6 on 2024-05-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('imgPath', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
                ('userRating', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('mpaaRatingType', models.CharField(max_length=10)),
                ('mpaaRatingLabel', models.CharField(max_length=100)),
            ],
        ),
    ]
