# Generated by Django 5.0.6 on 2024-05-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='movie_images/'),
        ),
    ]
