# Generated by Django 5.0.6 on 2024-05-30 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='imgPath',
        ),
    ]
